# fly.toml app configuration file generated for duration-pred-serve-2025-04 on 2025-04-04T10:09:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'duration-pred-serve-2025-04'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 9696
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
